# Add 'server' to any changes within 'server' folder or any subfolders
server:
  - server/**/*

# Add 'branding' to any file changes within 'honeywell' folder
branding: honeywell/*

# Add 'enhancement' label to any change to index.js file
enhancement:
  - src/*
  - package.json
  - pakcage-lock.json
  - config.schema.json

# Add 'workflow' to any changes within 'workflow' folder or any subfolders
workflow:
  - .github/workflows/*
